# Generated by Django 2.1.3 on 2018-12-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_auto_20181203_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='location',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
