# Generated by Django 2.1.3 on 2018-12-17 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0004_auto_20181217_0605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='user_id',
            new_name='user',
        ),
    ]
