# Generated by Django 2.1.3 on 2018-12-17 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0005_auto_20181217_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='user',
        ),
    ]
