# Generated by Django 2.1.3 on 2019-01-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0006_auto_20181217_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='Comments_datetime',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='post_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='post_datetime',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_email',
            new_name='email',
        ),
        migrations.AddField(
            model_name='posts',
            name='end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='image_url',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='start',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='target_type',
            field=models.CharField(choices=[('text', 'TextPositionSelector'), ('image', 'FragmentSelector')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('sound', 'Sound'), ('text', 'Text'), ('dataset', 'Dataset')], max_length=20, null=True),
        ),
    ]
