# Generated by Django 2.1.3 on 2019-01-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0007_auto_20190103_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='happened_on',
            field=models.DateField(null=True),
        ),
    ]
